# Generated by Django 3.0.3 on 2020-03-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20200302_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='maze',
            name='exit_room',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maze',
            name='start_room',
            field=models.IntegerField(default=0),
        ),
    ]
