# Generated by Django 3.0.3 on 2020-03-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20200302_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_maze',
            field=models.IntegerField(default=0),
        ),
    ]
