# Generated by Django 3.0.3 on 2020-03-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_auto_20200304_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.AddField(
            model_name='maze',
            name='seed',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='maze',
            name='exit_room',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='maze',
            name='start_room',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_maze',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_room',
            field=models.IntegerField(default=-1),
        ),
    ]
